---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-copilot-usage-lambda
  description: AWS Lambda function that collects GitHub Copilot usage history, teams, and team history for the Digital Landscape dashboard.
  annotations:
    github.com/project-slug: ONS-Innovation/github-copilot-usage-lambda
  tags:
    - python
    - aws-lambda
    - aws-eventbridge
  links:
    - url: https://ons-innovation.github.io/github-copilot-usage-lambda
      title: Copilot Usage Lambda Documentation
    - url: mailto:knowledge.exchange.hub@ons.gov.uk
      title: Contact
spec:
  type: service
  lifecycle: production
  owner: keh-dev
